from setuptools import setup, find_packages

setup(
    name='asx-bank-analyzer',
    version='0.1.0',
    description='A trading analysis system for ASX banks',
    author='Your Name',
    author_email='your.email@example.com',
    packages=find_packages(),
    install_requires=[
        'yfinance==0.2.28',
        'pandas==2.1.3',
        'numpy==1.24.3',
        'requests==2.31.0',
        'beautifulsoup4==4.12.2',
        'lxml==4.9.3',
        'ta==0.10.2',
        'pandas-ta==0.3.14b0',
        'python-dotenv==1.0.0',
        'schedule==1.2.0',
        'matplotlib==3.7.2',
        'seaborn==0.12.2',
        'plotly==5.17.0',
        'selenium==4.15.2',
        'webdriver-manager==4.0.1',
        'textblob==0.17.1',
        'vaderSentiment==3.3.2',
        'jinja2==3.1.2',
        'weasyprint==60.1',
        'pytest==7.4.3',
        'black==23.11.0',
        'flake8==6.1.0',
        'discord-webhook==1.3.0',
        'python-telegram-bot==20.6',
    ],
    python_requires='>=3.6',
)